# Generated by Django 4.2.26 on 2026-02-03 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0002_remove_book_isbn_remove_book_published_date_and_more"),
    ]

    operations = []
